title: "LittleFIve's Shangri-La | LittleFIve的大House"
description: "Wowwwwww"
url: ""
baseurl: ""
author: "LittleFIve"
paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
